### ISSUE TITLE
Don't change kor lang.

### ISSUE THREAD

**Issue by jy041118** [MCFT-Server/SimpleLogin#2]
한국어로 안바뀌는데 어떻게 바꾸는지 알려주세요

**Comment by wsj7178** [comment]
default-language: kor

**Comment by jy041118** [comment]
However, It doesn't work. So I had a default language to kor, but client send messeage "default-value default-value" fix plugin wsj7178 guy.

**Comment by wsj7178** [comment]
한국어로 하시지 ㅇㅅㅇ
현재 누킷이랑 플러그인 둘다 최신버전 사용중이신거 맞죠?
한번 확인해보겠습니다

**Comment by jy041118** [comment]
네 혹시 따옴표 붙이면 안되나요?

**Comment by wsj7178** [comment]
붙여도 상관 없습니다.
